Display load config warning only when protected configs in list
ISISComputingGroup/ibex_gui pull request #1177
Opened 2020-08-20 15:18 UTC by mihai-stfc

### Description of work

Changed the Load Configuration dialogue so that there is no protected configurations warning message when there are none in the list. 
If at least one protected configuration is in the dialogue list, then the message will be displayed.

### Ticket

https://github.com/ISISComputingGroup/IBEX/issues/5062

### Acceptance criteria

- Warning message and icon are shown only when there is a protected config in the selection list

### Unit tests

N/A

### System tests

N/A

### Documentation
N/A

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?
- [ ] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev)?

### Final Steps
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

2020-08-25 08:11 UTC, RaiBishal commented on base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java
> +     * Returns Configuration/Component names and their protection status, excluding the current configuration
Javadoc requires the first sentence to end with a full stop.

2020-08-25 08:11 UTC, RaiBishal commented on base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java
> +    public static Map<String, Boolean> mapNamesWithTheirProtectionFlagWithoutCurrent(Collection<ConfigInfo> infos) {
Not sure if this method is used anywhere else.

2020-08-25 08:11 UTC, RaiBishal commented on base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java
> +     * Checks if there is a protected configuration/comp within the given ConfigInfos objects
same as above.

2020-08-25 08:11 UTC, RaiBishal commented on base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java
> +        if (infos == null) {
Infos will never be null as it is always assigned in the constructor. However, It can be empty, so we should better check if it is empty.

2020-08-25 08:11 UTC, RaiBishal commented on base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java
> +    	return false;
Good to have one return statement rather than 3. Easier to debug If something goes wrong.

2020-08-25 08:11 UTC, RaiBishal requested changes
Some minor changes.

2020-08-28 13:58 UTC, JamesKingWork requested changes
See comments

2020-08-28 13:58 UTC, JamesKingWork commented on base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java
> +     * @param infos
Please give a description of infos

2020-08-28 13:58 UTC, JamesKingWork commented on base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java
> +        if (infos.isEmpty()) {
Suggestion: Use infos.stream().anyMatch(<predicate>) where predicate is the test for isProtected. See here for more details on anymatch https://www.geeksforgeeks.org/stream-anymatch-java-examples/. Stream can be a useful tool for situations like this

2020-08-28 13:58 UTC, JamesKingWork commented on base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java
> +        if (infos.isEmpty()) {
Though I agree we should check for emptiness and ideally wouldn't need null checks, I do think we should not remove null checks when we can't guarantee how `infos` is made. I suggest `if (infos == null || infos.isEmpty())` as the `||` is cutting so if infos is null then the check `infos.isEmpty()` will not be performed. Please do similar for the other places that we have removed the null check.

2020-08-28 13:58 UTC, JamesKingWork commented on base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java
> +        if (infos.isEmpty()) {
If you choose to implement this suggestion then there is no need for the empty test, but a null check would be useful

2020-08-28 13:58 UTC, JamesKingWork commented on base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/MultipleConfigsSelectionDialog.java
> +		{
Checkstyle may complain if the `{` is not on the same line as the if with a space between the `{` and the `)`

2020-08-28 13:58 UTC, JamesKingWork commented on base/uk.ac.stfc.isis.ibex.ui.configserver/src/uk/ac/stfc/isis/ibex/ui/configserver/dialogs/MultipleConfigsSelectionDialog.java
> +	            messageImageLabel.setImage(JFaceResources.
Checkstyle may complain about the indentation here. The call to setImage should be indented at the same level as the Label declaration

2020-08-28 13:58 UTC, JamesKingWork commented on base/uk.ac.stfc.isis.ibex.configserver/src/uk/ac/stfc/isis/ibex/configserver/configuration/ConfigInfo.java
> +    public static Boolean hasProtectedConfigs(Collection<ConfigInfo> infos) {
I would like for there to be unit tests on this method

2020-09-07 13:56 UTC, JamesKingWork approved these changes
Looks great!

2020-09-07 14:14 UTC, merged