Add CAEN v895 GUI
ISISComputingGroup/ibex_gui pull request #1202
Opened 2020-10-14 23:27 UTC by FreddieAkeroyd

### Description of work

Add GUI for CAEN v895

### Ticket

See ISISComputingGroup/IBEX#4915

### Acceptance criteria

*List the acceptance criteria for the PR. The aim is provide information to help the reviewer*

### Unit tests

*Give an overview of unit tests you have added or modified, if applicable. The aim is provide information to help the reviewer*

### System tests

*Mention any automated tests or manual tests that you have added or modified, if applicable. The aim is provide information to help the reviewer*

### Documentation
*Highlight and provide a link to any additions or changes to the documentation, if applicable. The aim is provide information to help the reviewer*

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?
- [ ] Have the changes been documented in the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev)?

### Final Steps
- [ ] Reviewer has moved the [release notes](https://github.com/ISISComputingGroup/IBEX/wiki/ReleaseNotes_Dev) entry for this ticket in the "Changes merged into master" section

2020-10-21 08:49 UTC, JamesKingWork requested changes
Mostly good, a couple of usability issues

2020-11-17 13:36 UTC, Tom-Willemsen commented
Noticed by @kjwoodsISIS : the font on the OPI is too small to be readable. Can we increase it's size please?

Compare with eurotherm OPI:
![image](https://user-images.githubusercontent.com/24375813/99396589-d61a6380-28d9-11eb-9d2c-ec187ba46e42.png)

2021-01-05 11:31 UTC, John-Holt-Tessella commented on base/uk.ac.stfc.isis.ibex.opis/resources/CAENv895.opi
> +    <tooltip>Disabled tabs are because Eurotherm is not active in IOC.</tooltip>
Can not see a script to disable tabs

2021-01-05 12:13 UTC, John-Holt-Tessella commented
Hopefully better 
![Uploading image.png…]()

2021-01-08 15:29 UTC, JamesKingWork approved these changes

2021-01-08 15:30 UTC, merged