Ticket5949 musr steering
ISISComputingGroup/ibex_gui pull request #1240
Opened 2021-01-14 11:44 UTC by rerpha

### Description of work

OPI for steering the horizontal and vertical magnets via two kepcos

### Ticket

ISISComputingGroup/IBEX#5949

### Acceptance criteria

See ticket

### Unit tests

None, just an OPI 

### System tests

""

### Documentation

""

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?
- [ ] Is there associated PR for the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)?

### Final Steps
- [ ] Reviewer has also merged the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)

2021-01-18 16:59 UTC, DominicOram requested changes
Minor changes in xml. Can you please do the following:
* Add a brief note on the steering magnets to the development wiki, probably somewhere under https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Magnets. Specifically that the stop is done as a custom record
* Can you make an icon please?
* There is currently no indication that the stop button has done anything, can you show the on/off status of each power supply so that you can actually see it turn off?
* The VI turns the power supplies on every time it is started, I don't think we want the OPI to do that but if we're giving the scientist a way to turn it off we need a way to turn it on, can we add a button for this?
* In the VI there is a save button, we have no equivalent here @Kevin-Woods-Tessella do you know if this has already been discussed with the scientists? They're happy not to have this feature?

2021-01-18 16:59 UTC, DominicOram commented on base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
> +        <categories />
This should probably live in the magnets category

2021-01-20 13:48 UTC, kjwoodsISIS commented
The `Save` button writes the two setpoints to the `C:\LabVIEW Modules\Instruments\MUSR\MuSR Steering.ini` file.  The `.ini` file is read on start of the VI and the setpoint values populated with those saved previously.  Presumably autosave would achieve much the same effect (except the scientist would not have the discretion to choose when the save event happens).

2021-01-20 17:02 UTC, DominicOram commented
Thanks @Kevin-Woods-Tessella!

> Presumably autosave would achieve much the same effect
I think this might need a bit more discussion, we tend not to autosave set points. The principal being that an IOC restart does not change the state of the hardware. I'm not saying we shouldn't do it but it requires a bit of thought.

> (except the scientist would not have the discretion to choose when the save event happens)
I wasn't sure if this was a hard requirement for the scientists or not?

@rerpha I think the answer is to have a brief discussion with a few developers and the instrument scientists. Can you make a ticket?

2021-01-26 14:09 UTC, DominicOram approved these changes
I made some minor edits to get the start/stop buttons to work repeatedly. Otherwise good

2021-01-26 14:09 UTC, merged