Display the name and path of the saved parameters file
ISISComputingGroup/ibex_gui pull request #1250
Opened 2021-02-05 12:47 UTC by mihai-stfc

### Description of work

Added label which displays the name and location of the saved parameters file that has been loaded.

### Ticket

https://github.com/ISISComputingGroup/IBEX/issues/5969

### Acceptance criteria

1. The Script Generator displays the name of the saved parameters filein an obvious location (e.g. in the window title bar, or just below the menu bar).

### Unit tests

N/A

### System tests

N/A

### Documentation
N/A

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?
- [ ] Is there associated PR for the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)?

### Final Steps
- [ ] Reviewer has also merged the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)

2021-02-05 14:32 UTC, Tom-Willemsen requested changes
- When I first open the script generator this is the message I get, it is not very user-friendly. Other programs use a default filename (e.g. Notepad++ uses `new 1`, word uses `Document1.docx`). In any case we should make it clear that they are unsaved, and when the user goes to save we should do a "save as" to allow them to choose a name.

![image](https://user-images.githubusercontent.com/24375813/107045195-24dee780-67bd-11eb-81fd-d88e238f3738.png)

- After editing my parameters and saving them with a filename, the "currently editing file" label still shows blank. I have to explicitly load them back in to get the "currently editing file" label to change, this is confusing
- The ticket has mockups for save & save as buttons (perhaps with `save as` as a dropdown option) but I don't see that these have been implemented - did you forget to push a commit?
- The mockups on the ticket include some concept of the document being "dirty" and therefore needing saving. The mockups indicate this with a `(*)` next to the filename but I don't see that this has been implemented (did you forget to push a commit?)

Happy to talk about any of this in more detail if you like.

2021-02-05 14:57 UTC, kjwoodsISIS commented
Yes, I agree with @Tom-Willemsen .  When the user creates a new Parameters file, it will not yet have a name, so we should provide a default name or a message to say the file has not yet been saved.  Some thing like this:
   `Editing file: Document1.json`  or
   `Editing file: <file-has-not-yet-been-saved>`

2021-02-09 16:35 UTC, Tom-Willemsen reviewed
Functionally this is good, but it needs some form of tests adding.

I think you should be able to test most of this logic at the unit test level (you may find it easier to first move the logic into the model rather than the viewmodel to make it more testable), but if that turns out to be too hard, we should write a squish test for it. Shout on technical channel on teams if you need help writing a squish test and I (or someone else) can show you how to do it.

2021-02-09 16:35 UTC, Tom-Willemsen commented on base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
> +        		String displayString = parametersFileDisplayString + " (*)";
Can we make `" (*)"` a constant in the code to avoid duplication of it in multiple places.

2021-02-15 17:49 UTC, mihai-stfc commented
https://github.com/ISISComputingGroup/System_Tests_UI_E4/pull/85

2021-02-17 16:34 UTC, Tom-Willemsen approved these changes

2021-02-17 16:35 UTC, merged