Ticket5811 table bug fixing
ISISComputingGroup/ibex_gui pull request #1318
Opened 2021-06-23 14:01 UTC by JamesKingWork

### Description of work

- Correct how we update actions in the script generator actions table so we don't lose and reapply focus
- Fix some minor bugs discovered whilst playing around

### Ticket

https://github.com/ISISComputingGroup/IBEX/issues/5811

### Acceptance criteria

#### To test:

- Add lots of rows very quickly and then try editing and tabbing between cells whilst the script generator validates and calculates an estimated time for all the actions
- Confirm that general actions still work such as changing script definitions, adding, removing, moving actions up and down, saving and reloading parameters 

### Unit tests

*Give an overview of unit tests you have added or modified, if applicable. The aim is provide information to help the reviewer*

### System tests

*Mention any automated tests or manual tests that you have added or modified, if applicable. The aim is provide information to help the reviewer*

### Documentation
*Highlight and provide a link to any additions or changes to the documentation, if applicable. The aim is provide information to help the reviewer*

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?
- [ ] Is there associated PR for the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)?

### Final Steps
- [ ] Reviewer has also merged the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)

2021-06-23 14:23 UTC, JamesKingWork commented on base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ActionsViewTable.java
> +		var element = viewer.getElementAt(row);
Fixes NullPointerException where the element is null so editElement cannot handle it.

2021-06-23 14:23 UTC, JamesKingWork commented on base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
> -     * A light orange to use when validity checks may be incorrect e.g. for when using an unsupported language.
Not used anywhere so removed

2021-06-23 14:23 UTC, JamesKingWork commented on base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
> - * @author James King
Don't know when this was added, but certainly hasn't been just me so removed

2021-06-23 14:24 UTC, JamesKingWork commented on base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
> -    actionChangeHandler(viewTable, btnGenerateScript, btnSaveParam, btnSaveParamAs, true);
The actionChangeHandler should only be called when the action change is propagated from below.

2021-06-23 14:25 UTC, JamesKingWork commented on base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
> +        viewTable.setCellFocus(insertionLocation, ActionsViewTable.NON_EDITABLE_COLUMNS_ON_LEFT);
Set the cell focus to the first editable column

2021-06-23 14:26 UTC, JamesKingWork commented on base/uk.ac.stfc.isis.ibex.ui.scriptgenerator/src/uk/ac/stfc/isis/ibex/ui/scriptgenerator/views/ScriptGeneratorViewModel.java
> -    List<ScriptGeneratorAction> actions = scriptGeneratorModel.getActions();
Moved into the update calls in the various columns as this seemed more in-keeping with the swt tables

2021-07-02 14:19 UTC, SamJenkins1 requested changes
Adding a large number of rows quickly, and then changing the script definition to one with global variables causes the script genderator to crash.

Other than that everything seems to look fine, a couple of comments on the code.

2021-08-11 16:08 UTC, JamesKingWork commented
> Adding a large number of rows quickly, and then changing the script definition to one with global variables causes the script genderator to crash.

I couldn't cause the script generator to crash doing this, but it did write nasty things to the log that looked like it could be the symptom of what would have caused a crash for you. I have now rewritten the algorithm to prevent this issue, I hope it also corrects the crashing that you saw, let me know if it doesn't so we can look through together to see what is causing it.

2021-08-20 11:05 UTC, SamJenkins1 approved these changes
With the changes made and handling of the edge case found, this is good to go in.

2021-08-20 11:10 UTC, merged