Created OPI for Wish Jaws but a couple of PVs are missing
ISISComputingGroup/ibex_gui pull request #1379
Opened 2021-11-23 16:52 UTC by daryakoskeroglu

### Description of work

Created OPI for Wish Jaws but a couple of PVs are missing.

PVs that are connected are Vertical and Horizontal Gap and their setpoints.

The OPI is created based on the VI:  (located here: C:\LabVIEW Modules\Instruments\WISH\WISH Jaws).)

![WISH Front Panel](https://user-images.githubusercontent.com/56968931/143065755-73a1c3bb-3af3-49f4-9c2c-2820a4d6c1a2.PNG)

There is also a Setup Dialogue to set gaps which is written to the text file on LabVIEW. This gaps could be set via editing the text file directly which then can be seen in the Front Panel. However, WISH scientists do not use neither Setup Dialogue nor text file.

Also they added that:

"The jaws are jittering a bit and sometimes to get the right value you need to send a value that is a bit off and repeat the operation several times so actually we just set values in the VI and drive."

### Things needs to be done 

1. Populate "Experiment Type" menu, possibly create an enum PV for this.
2. Connect Resolution menu, Dead Band, Position error and Activity LEDs , and set and start/stop buttons.

### Ticket

[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/6033)
---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?
- [ ] Is there associated PR for the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)?

### Final Steps
- [ ] Reviewer has also merged the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)

2021-11-25 09:49 UTC, JamesKingWork requested changes
The OPI is simple and matches the VI which is good. We have a nice more_detail_manager.opi which provides a graphical view and more control over the jaws, can we add a button that opens this more_details_manager with the wish jaws. An example of this is in the nimrod_manager.opi and gem_manager.opi with the button "Jaws Manager". It would probably be good to place this in the same grouping container where the gaps can be set as the information in the more_detail_manager.opi is most connected to those gaps.

2021-12-14 13:47 UTC, Adam-Szw commented
The OPI looks good and passes `check_opi_format` test. The _Jaws Manager_ button from James' suggestion was added. Just a small change request:
- Please add entry for the OPI to `opi_info.xml` so that this OPI can be selected from the client.
I expect that functionality of the OPI and/or IOC will be reviewed here https://github.com/ISISComputingGroup/IBEX/issues/6917 so I'm leaving PV connectivity out here.

2021-12-15 16:24 UTC, daryakoskeroglu commented
> The OPI looks good and passes `check_opi_format` test. The _Jaws Manager_ button from James' suggestion was added. Just a small change request:
> 
> * Please add entry for the OPI to `opi_info.xml` so that this OPI can be selected from the client.
>   I expect that functionality of the OPI and/or IOC will be reviewed here [WISH: Connect PVs to WISH Jaws OPI IBEX#6917](https://github.com/ISISComputingGroup/IBEX/issues/6917) so I'm leaving PV connectivity out here.

Thanks for the review, I've updated opi_info.xml

2021-12-16 12:07 UTC, Adam-Szw approved these changes

2021-12-16 12:07 UTC, Adam-Szw commented on base/uk.ac.stfc.isis.ibex.opis/resources/opi_info.xml
> +        <path>jaws/jaws_managers/WISH_Jaws.opi</path>
There was a typo here, I fixed it quickly

2021-12-16 12:08 UTC, Adam-Szw approved these changes

2021-12-16 12:08 UTC, Adam-Szw approved these changes

2021-12-16 12:11 UTC, merged