Ticket 3736
ISISComputingGroup/ibex_gui pull request #1452
Opened 2022-07-29 08:51 UTC by boeuf-codes

### Description of work

- Added action to the block context menu to navigate to run control settings
- Edited title in block configuration dialogue to clarify runcontrol settings there are _default_  settings rather than current.

### Ticket

[*Link to Ticket #3736*](https://github.com/ISISComputingGroup/IBEX/issues/3736)

### Acceptance criteria

- be able to open the runcontrol settings menu via the context menu of a block.
- make clearer the run control settings entered there are the default runcontrol values, to help make the distinction between those and the current runcontrol settings accessed via the menu bar.

### Unit/System tests
n/a

### Manual tests
See test: **section 20, test 27**

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] If the change is to an OPI, does the `check_opi_format.py` script in [C:\Instrument\Dev\ibex_gui\base\uk.ac.stfc.isis.ibex.opis](https://github.com/ISISComputingGroup/ibex_gui/blob/master/base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py) pass?
- [ ] Do the changes function as described and is it robust?
- [ ] Is there associated PR for the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)?

### Final Steps
- [ ] Reviewer has also merged the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)

2022-08-04 15:27 UTC, JackEAllen requested changes
Thanks for working on this. From testing on the GUI, your changes act as expected 🥇
 
Overall this is really good. Mainly just needs a merge conflict resolving. I have left a few minor changes and also the odd nit-picks which you're more than welcome to decide on whether you agree with or not. 
I'm going to place this into rework so you can make the minor changes I've suggested and fix the merge conflict, then I'm happy to pick it back up to review again after.

2022-08-04 15:27 UTC, JackEAllen commented on base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/BlocksMenu.java
> +    public BlocksMenu(DisplayBlock displayBlock, IHandlerService handlerService) {
Can we add `handlerService` to the docstring?

2022-08-04 15:27 UTC, JackEAllen commented on base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/BlocksMenu.java
> +
NITPICK: Could we remove this dead space at the end?

2022-08-04 15:27 UTC, JackEAllen commented on base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/BlocksMenu.java
> +        final IAction viewRunControlSettingsAction = new Action(VIEW_RUN_CONTROL_SETTINGS) {
Do you think it's worth adding a brief comment here just to describe the below block?

2022-08-04 15:27 UTC, JackEAllen commented on base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/Group.java
> +	public Group(Composite parent, int style, DisplayGroup group, GroupsPanel panel, IHandlerService handlerService) {
Can we update the docstring to include `handlerService`

2022-08-04 15:27 UTC, JackEAllen commented on base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/GroupsPanel.java
> +	public GroupsPanel(Composite parent, int style, IHandlerService handlerService) {
Can we update the docstring to include `handlerService`

2022-08-04 15:27 UTC, JackEAllen commented on base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/views/BlocksView.java
> +	public void createPartControl(final Composite parent, MApplication app, EModelService modelService, IHandlerService handlerService) {
Can we update the docstring to include `handlerService`

2022-08-08 08:51 UTC, boeuf-codes commented on base/uk.ac.stfc.isis.ibex.ui.runcontrol/src/uk/ac/stfc/isis/ibex/ui/runcontrol/dialogs/EditRunControlDialog.java
>  	 * @param runControlServer the Run Control server
It seems I had already moved these to the correct place but not deleted here, so have just removed.

2022-08-08 09:34 UTC, JackEAllen commented on base/uk.ac.stfc.isis.ibex.ui.blocks/src/uk/ac/stfc/isis/ibex/ui/blocks/groups/BlocksMenu.java
> +    public BlocksMenu(DisplayBlock displayBlock, IHandlerService handlerService) {
Thanks for adding this. I would say it describes `handlerService` pretty well.

2022-08-08 10:18 UTC, boeuf-codes commented
Commits for rework:
- Docstrings & comment adding https://github.com/ISISComputingGroup/ibex_gui/pull/1452/commits/2b24de31d3c11f6bcbf46c8348f2604a0cb0a4a0
-  Merging master https://github.com/ISISComputingGroup/ibex_gui/pull/1452/commits/de49d8771bcd423d03b649f379066818e0ddeb80

2022-08-08 13:55 UTC, JackEAllen approved these changes
Thanks for making these changes and merging in the conflict. Have tested again and happy to put this through now 👍

2022-08-08 13:56 UTC, merged