Ticket5880_chronus_magnet_status
ISISComputingGroup/ibex_gui pull request #1683
Opened 2024-03-18 15:32 UTC by isaachilly

### Description of work

Copied and modified previous work done on the ARGUS magnet status OPI. 

Searched the [DB records](https://github.com/ISISComputingGroup/EPICS-ioc/tree/4eb7c310cfa030f2a35da9ab3cbe060c8bb9f3eb/SCHNDR/SCHNDR-IOC-01App/Db) for the temperature PVs for the magnets but they are still not monitored, which was the same case on Argus.

### Ticket

- https://github.com/ISISComputingGroup/IBEX/issues/5880

### Acceptance criteria

1. The CHRONUS Magnet Status OPI displays the following fields.
   1. Magnet Temperature
   1. Magnet Water Flow rate (l/m) (to 1 decimal place)
   1. Klixon status (FAULT/OK)

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] If the change is to an OPI, does the `check_opi_format.py` script in [C:\Instrument\Dev\ibex_gui\base\uk.ac.stfc.isis.ibex.opis](https://github.com/ISISComputingGroup/ibex_gui/blob/master/base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py) pass?
- [ ] Do the changes function as described and is it robust?
- [ ] Is there associated PR for the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)?

### Final Steps
- [ ] Reviewer has also merged the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)

2024-03-26 12:16 UTC, LowriJenkins requested changes
Given how similar the two OPI's are, it should probably all be pulled out into a an OPI that takes a macro instead of `CHRONUS` or `ARGUS` and then use a linking container to set that for both OPI's Ive made some changes to make the CHRONUS opi comply better with our standards so if you just pull that out into an opi that both load in via linking container it should all work

2024-03-26 12:41 UTC, isaachilly commented
Yes I thought this too however I assumed we'd make another ticket maybe to create the combined OPI as that's not what this ticket is about.

2024-03-26 12:43 UTC, LowriJenkins commented
better to think of this as a parent opi and a way to have reduced code duplication

2024-03-26 12:46 UTC, isaachilly commented
Yeah, I can do the work that's no problem I just assumed we want to limit the scope of tickets so we know where to find changes etc.

2024-03-26 14:31 UTC, LowriJenkins commented
Better to avoid code duplication in the first place as it can more easily lead to errors, especially if we want to change things about these opi's later

2024-03-26 14:45 UTC, isaachilly commented
Yeah I agree, it's just not the ticket to also change Argus so I thought we'd create a new one for it so in future people know where to find things. I don't mind, you think should do in this one?

2024-03-26 14:48 UTC, LowriJenkins commented
Yes, its the kind of minor change that is better accomplished as part of this, doing it entirely separately will simply create more work.

2024-03-27 09:57 UTC, LowriJenkins approved these changes

2024-03-27 09:57 UTC, merged