Ticket8235 ibexgui
ISISComputingGroup/ibex_gui pull request #1694
Opened 2024-04-19 13:08 UTC by danielmaclaren

### Description of work

Updated the buttons within the configserver folder

### Ticket

[*Link to Ticket*](https://github.com/ISISComputingGroup/IBEX/issues/8235)

### Acceptance criteria

Button functionality remains the same as before

---

#### Code Review

- [ ] Is the code of an acceptable quality?
- [ ] If the change is to an OPI, does the `check_opi_format.py` script in [C:\Instrument\Dev\ibex_gui\base\uk.ac.stfc.isis.ibex.opis](https://github.com/ISISComputingGroup/ibex_gui/blob/master/base/uk.ac.stfc.isis.ibex.opis/check_opi_format.py) pass?
- [ ] Do the changes function as described and is it robust?
- [ ] Is there associated PR for the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)?

### Final Steps
- [ ] Reviewer has also merged the [release notes](https://github.com/ISISComputingGroup/IBEX/blob/master/release_notes/ReleaseNotes_Upcoming.md)

2024-04-23 09:51 UTC, zsoltkebel requested changes

2024-05-16 11:28 UTC, Chsudeepta requested changes
There are multiple checkstyle issues. Mostly because of unused imports and unused private variables.

2024-05-16 15:08 UTC, Chsudeepta approved these changes

2024-05-22 09:52 UTC, zsoltkebel approved these changes

2024-05-22 10:56 UTC, merged