Fix for missing icon for Litron Power OPI
ISISComputingGroup/ibex_gui pull request #1757
Opened 2024-12-10 18:47 UTC by Chsudeepta

### Description of work

Fixes the GUI build issue due to missing icon and thumbnail for Litron Power OPI. 
Copied the default cog.png and cog_tb.png files, and renamed for a quick fix.

### Acceptance criteria
Code should build successfully by running the build.bat from ibex_gui\build

2024-12-11 10:23 UTC, rerpha requested changes
I think we should design an icon rather than just use the default cog. it probably should have been done in the original ticket really.

2024-12-11 10:23 UTC, rerpha commented on base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/ComponentIcons.java
> +            case LITRONPOWER:
i've already done this in https://github.com/ISISComputingGroup/ibex_gui/commit/74ce4845f5b7067a54dd4e45347e0a3de5035838

2024-12-11 10:24 UTC, rerpha commented on base/uk.ac.stfc.isis.ibex.ui.devicescreens/src/uk/ac/stfc/isis/ibex/ui/devicescreens/ComponentIcons.java
> +            case LITRONPOWER:
no I haven't, sorry...

2024-12-12 10:30 UTC, rerpha commented
right, actually, the keyence one is a picture of a laser so we can use that - you should be able to just add LITRONPOWER as an additional case above line 207 so that both use that icon.

2024-12-12 12:08 UTC, Chsudeepta commented
Made the changes suggested. Please check.

2024-12-12 12:22 UTC, rerpha approved these changes

2024-12-12 12:22 UTC, merged